# Site settings
title: julius@png:~
description: >-
  julius tuckayo · data professional · manager data and digital @ nasfund
baseurl: ""
url: "https://jtuckayo.github.io"
github_username: jtuckayo

# Header nav order
header_pages:
  - projects.markdown
  - cv.markdown
  - now.markdown
  - about.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Minima skin (we override most things in main.scss anyway)
minima:
  skin: dark

exclude:
  - jtuckayo.github.io/
  - vendor/
